pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Đây là Building...'
            }
        }

        stage('Test') {
            steps {
                echo 'Đây là testing...'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Đây là Deploy...'
            }
        }
    }
}
